apiVersion: v1
kind: ConfigMap
metadata:
  name: broker-service-envs
data:
  ACCOUNTSERVICE_HOSTANDPORT: "accountservice:8080"
  PRICINGSERVICE_HOSTANDPORT: "pricing-service:8080"
  ENGINE_HOSTANDPORT: "engine:8080"
  PROXY_PREFIX: "broker-service"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker-service
spec:
  selector:
    matchLabels:
      app: broker-service
  template:
    metadata:
      labels:
        app: broker-service
    spec:
      nodeSelector:
        kubernetes.io/arch: s390x
      containers:
        - name: broker-service
          image: quay.io/mmondics/easytrade-broker-service:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_CONNECTIONSTRING
              valueFrom:
                configMapKeyRef:
                  name: connection-strings
                  key: DOTNET_CONNECTION_STRING_MYSQL
          envFrom:
            - configMapRef:
                name: broker-service-envs
            - configMapRef:
                name: feature-flag-service-setup
          securityContext:
            runAsUser: 0
          resources:
            requests:
              cpu: 150m
              memory: 350Mi
            limits:
              memory: 350Mi
        - name: mysql-debugger
          image: quay.io/fedora/fedora-minimal
          command: ["sleep", "3600"]
          securityContext:
            runAsUser: 0
          resources:
            requests:
              cpu: 20m
              memory: 50Mi
            limits:
              memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: broker-service
spec:
  type: ClusterIP
  selector:
    app: broker-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
