apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-mysql
spec:
  selector:
    matchLabels:
      app: db-mysql
  template:
    metadata:
      labels:
        app: db-mysql
    spec:
      nodeSelector:
        kubernetes.io/arch: s390x
      containers:
        - name: db-mysql
          image: quay.io/mmondics/easytrade-db-mysql:1.0.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "password"
          resources:
            requests:
              cpu: 40m
              memory: 1.5Gi
            limits:
              memory: 1.5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: db-mysql
spec:
  type: ClusterIP
  selector:
    app: db-mysql
  ports:
    - name: db-mysql
      port: 3306
      targetPort: 3306
