name: "fraud_preprocessor"
backend: "python"
max_batch_size: 0

input [
  {
    name: "raw_input"
    data_type: TYPE_FP32
    dims: [1,9]
  }
]

output [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [1,9]
  }
]