apiVersion: v1
kind: ConfigMap
metadata:
  name: broker-service-envs
data:
  ACCOUNTSERVICE_HOSTANDPORT: "accountservice:8080"
  PRICINGSERVICE_HOSTANDPORT: "pricing-service:8080"
  ENGINE_HOSTANDPORT: "engine:8080"
  PROXY_PREFIX: "broker-service"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker-service
spec:
  selector:
    matchLabels:
      app: broker-service
  template:
    metadata:
      labels:
        app: broker-service
    spec:
      containers:
        - name: broker-service
          # tag 1.0.0 does not call a fraud detection model.
          # tag 2.0.0-fraud-ensemble uses triton ensemble. use TRITON_FRAUD_URL = .../v2/models/fraud_ensemble/infer
          # tag 2.0.0-fraud-model calls the model directly with preprocessing done within broker service. Does not use triton ensemble. use TRITON_FRAUD_URL = .../v2/models/fraud_model/versions/1/infer
          # image: quay.io/mmondics/easytrade-broker-service:1.0.0
          # image: quay.io/mmondics/easytrade-broker-service:2.0.0-fraud-model
          image: quay.io/mmondics/easytrade-broker-service:2.0.0-fraud-ensemble
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_CONNECTIONSTRING
              valueFrom:
                configMapKeyRef:
                  name: connection-strings
                  key: DOTNET_CONNECTION_STRING
            - name: ENABLE_FRAUD_DETECTION
              value: 'true'
            - name: TRITON_FRAUD_URL
              value: 'http://svc-triton-accelerated-easytrade.apps.atsocpd1.dmz/v2/models/fraud_ensemble/infer'
          envFrom:
            - configMapRef:
                name: broker-service-envs
            - configMapRef:
                name: feature-flag-service-setup
          resources:
            requests:
              cpu: 150m
              memory: 350Mi
            limits:
              memory: 350Mi
---
apiVersion: v1
kind: Service
metadata:
  name: broker-service
spec:
  type: ClusterIP
  selector:
    app: broker-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
