apiVersion: v1
kind: ConfigMap
metadata:
  name: connection-strings
data:
  JAVA_CONNECTION_STRING: jdbc:mysql://db:3306/TradeManagement?user=root&password=password&useSSL=false&allowPublicKeyRetrieval=true
  DOTNET_CONNECTION_STRING: Server=db;Port=3306;Database=TradeManagement;User Id=root;Password=password;
  GO_CONNECTION_STRING: root:password@tcp(db:3306)/TradeManagement
